\documentclass{article}

\title{imsbInfer - testing Normalization nr 2}
\author { W.E. Wolski }


%\VignetteIndexEntry{Getting started}


\begin{document}
\SweaveOpts{concordance=TRUE}
\maketitle


\section{Load the data}

This is how you would read your data
<<eval=TRUE,results=hide>>=
rm(list=ls())
library(imsbInfer)
@


<<readdataremovedecoys>>=
data(feature_alignment_requant)
SwathDat = read2msExperiment(feature_alignment_requant)
SwathDat = removeDecoys(SwathDat)

@

<<>>=
xx<-colnames(SwathDat$Intensity)
xx<-sub("chludwig_","",xx)
xx<-sub("_SW$","",xx)
SwathDat = mycolnames(SwathDat,xx)
head(SwathDat$Intensity)

@

<<>>=
SwathDat = orderByRT(SwathDat)
pairsRatio(SwathDat$Intensity[,1:3],SwathDat$RT,ylim=c(-8,8),main="ratio vs RT")

@

<<echo=FALSE, results=hide>>=
dim(SwathDat)
names(SwathDat)
sum(is.na(SwathDat$Intensity))
colnames(SwathDat$Intensity)
colnames(SwathDat$pepinfo)
@

pairsplot

<<fig=TRUE>>=
mypairs(SwathDat$Intensity[,1:3],log="xy",main="pairsplot")

@

<<fig=TRUE>>=
pairsQQ(SwathDat$Intensity[,1:3],main="qqplot")

@

Remove low and high RT ranges

<<fig=TRUE>>=
SwathDatT = subset(SwathDat, SwathDat$RT < 7000 & SwathDat$RT > 1000)
pairsRatio(SwathDatT$Intensity[,1:3],SwathDatT$RT,ylim=c(-8,8),main="ratio vs RT")
@


<<fig=TRUE,width=9,height=6>>=
cors = cor(SwathDatT$Intensity, use="na.or.complete",method="spearman")
dim(cors)
par(mar = c(7,7,1,1))
imagelabels(cors)

@


<<fig=TRUE>>=
hist(cors[upper.tri(cors)],main="histogram of correlations")
@


\section{RT normalization}

\subsection{doing it for two samples}


<<fig=TRUE,width=10, height=10,echo=FALSE,results=hide>>=
par(mfrow=c(1,3))

SwathDatT$intensityasinh = asinh(SwathDatT$Intensity)

aref = SwathDatT$intensityasinh[,1]
data = SwathDatT$intensityasinh[,3]

par(mfrow=c(2,2))

plot(SwathDatT$RT,aref -  data,pch=".",ylim=c(-4,4))
abline(h=0,col=2,lwd=2)

length(aref)
length(SwathDatT$RT)

###############

tmp2r = correctIntRTv2(aref, SwathDatT$RT ,scale=TRUE, k=101,plot=F)
tmp2d = correctIntRTv2(data, SwathDatT$RT ,scale=TRUE, k=101,plot=F)

plot(SwathDatT$RT, tmp2r-tmp2d,pch=".")
abline(h=0,col=2,lwd=2)

tmp = correctIntRTv2(aref, SwathDatT$RT ,scale=FALSE, k=101,plot=F)
plot(SwathDatT$RT,aref -  tmp,type="l",pch=".")

@

\subsection{Doing it for a dataset}

<<wholeDataset,fig=TRUE>>=

SwathDatT$Intensity = asinh(SwathDatT$Intensity)

tmp = correctIntRTv2(SwathDatT,k=301,scale=TRUE)
tmp$Intensity = sinh(tmp$Intensity)
pairsRatio(tmp$Intensity[,1:3],tmp$RT,ylim=c(-6,6),main="ratio vs RT")

@


<<fig=TRUE,width=9,height=5>>=
cors2 = cor(tmp$Intensity, use="na.or.complete",method="spearman")
par(mar = c(7,7,1,1))
imagelabels(cors2)

@


<<fig=TRUE>>=
hist(cors2[upper.tri(cors2)],add=F,main="histogram of correlations")
hist(cors[upper.tri(cors)],add=T,density=10,angle = 45, col = NULL)
@

\section{Analysing Peptides with various charge states}

<<>>=
head(SwathDat$pepinfo)
sum(duplicated(SwathDat$pepinfo$sequence))
@

\end{document}
